### ISSUE TITLE
issues while running quickstart for pgvector

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain-postgres#180]
1. initialization
 
the line that initializes the table uses the wrong variable (engine instead of pg_engine) and uses a public method, but the method is actually private

```python
await pg_engine._ainit_vectorstore_table(
    table_name=TABLE_NAME,
    vector_size=VECTOR_SIZE,
)
```

2. initializing twice raises an exception (should we have create if not exists semantics as well?) Users may want to have the code live in their app lifespan for simplicity (instead of doing some logic on server deployment)

3. cohere embeddings fails due to cohere model not being specified. 

4. using pgvectorstore create fails w/ an exception (
AttributeError: 'AsyncEngine' object has no attribute '_run_as_async')

```python
store = await PGVectorStore.create(
    engine=engine,
    table_name=TABLE_NAME,
    # schema_name=SCHEMA_NAME,
    embedding_service=embedding,
)
```

---

got stuck at this stage

**Comment by averikitsch** [comment]
1. Use the public method, see here https://github.com/langchain-ai/langchain-postgres/blob/22f4f474acf24bc909696c7346b9a561b384a882/langchain_postgres/v2/engine.py#L251. We can use the double underscore to remove access to the semi private method. The semi private should only be used by Async experts. 
2. This is a bad practice to keep this in application code. Users can wrap the error if they want to ignore the best practice. Users can also use overwrite in the init call. We want this to be enterprise quality by enforcing this.
3. We will fix this. 
4. What engine did you pass in? I’ll need to reproduce.

**Comment by eyurtsev** [comment]
> 1. ainit_vectorstore_table

yep confirmed was an issue just b/c of engine vs. pg_engine

> 2. This is a bad practice to keep this in application code. Users can wrap the error if they want to ignore the best practice. Users can also use overwrite in the init call. We want this to be enterprise quality by enforcing this.

OK skipping

4. What engine did you pass in? I’ll need to reproduce.

not sure can try again, i running through the cells one by one

**Comment by dishaprakash** [comment]
1. & 4. Are being caused by the use of variable engine instead of pg_engine. 

3. The PGVector example notebook mentioned this way of initializing the cohere embedding so I left that in. I'll update it to mention the model name.

Sorry about the oversight. I'll make the changes

**Comment by dishaprakash** [comment]
The above changes are being made in https://github.com/langchain-ai/langchain-postgres/pull/183
